// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['App']['Add'](arg1, arg2);
}

export function Divide(arg1, arg2) {
  return window['go']['main']['App']['Divide'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Multiply(arg1, arg2) {
  return window['go']['main']['App']['Multiply'](arg1, arg2);
}

export function ProcessText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessText'](arg1, arg2, arg3, arg4);
}

export function Subtract(arg1, arg2) {
  return window['go']['main']['App']['Subtract'](arg1, arg2);
}
